import type { Metadata } from "next";
import "./globals.css";

import { Inter as FontSans } from "next/font/google"
 
import { cn } from "@/lib/utils"
import SiteNav from "@/components/landing/site-nav";
import SiteFooter from "@/components/landing/site-footer";
import Footer from "@/components/landing/footer";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body
        className={cn(
          "w-full min-h-screen bg-background font-sans antialiased ",
          fontSans.variable
        )}
      >
            <div className="flex  flex-col min-h-screen bg-background">
            <SiteNav />
            {children}
            <Footer />
            <SiteFooter />
            </div>
            </body>
    </html>
  );
}
